# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: visualCaseGen CI tests

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "ci" ]

#permissions:
#  contents: write

jobs:
  ci_tests:
    name: visualCaseGen CI tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
      - name: Run unittests
        run: pytest tests/1_unit
        

